# Generated by Django 4.1.2 on 2022-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=50, null=True, verbose_name='Сумма')),
                ('category', models.CharField(choices=[('1Продукты', 'Продукты'), ('1Проезд', 'Проезд'), ('1Баловашки', 'Баловашки'), ('1Прочее', 'Прочее')], max_length=50, null=True, verbose_name='Категория')),
                ('budget', models.CharField(choices=[('1Алихан', 'Алихан'), ('1Таня', 'Таня'), ('1Личное Алихан', 'Личное Алихан'), ('1Личное Таня', 'Личное Таня')], max_length=50, verbose_name='Бюджет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
    ]
