# Generated by Django 4.1.2 on 2022-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_budget_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='Описание'),
        ),
    ]
