# Generated by Django 4.1.2 on 2022-11-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.CharField(choices=[('Алихан', 'Алихан'), ('Таня', 'Таня')], default='Алихан', max_length=50, verbose_name='Бюджет'),
        ),
    ]
